### ISSUE TITLE
Missing markdown file from Chapter 01 setup

### ISSUE THREAD

**Issue by CandidKilsborne** [PacktPublishing/ASP.NET-9-Web-API-Cookbook#1]
👋 Hey! TR here and figured this might be helpful on some of the code / document related items should they arise.

Chapter 1 has a reference to the `technical-requirements.md` file but it's missing from the repo.

https://github.com/PacktPublishing/ASP.NETCore9-WebApi-Cookbook/tree/main/docs/technical-requirements.md

**Comment by lavedon** [comment]
yikes! thanks, I actually meant to remove that mention. Glad you caught it.
