### ISSUE TITLE
Nuget Package Vulnerabilities on Chapter 02 Projects

### ISSUE THREAD

**Issue by CandidKilsborne** [PacktPublishing/ASP.NET-9-Web-API-Cookbook#2]
Might be due to Preview versions of both .NET and Nuget packages but might be worth keeping an eye on.

![image](https://github.com/user-attachments/assets/0ac2a873-7de3-4932-96a2-b32651a7de31)

**Comment by lavedon** [comment]
Thanks much for pointing that out.  Yes, packages have been updated to latest recommendations with the official release of .NET 9. Appreciate it!
